/*
1525. Number of Good Ways to Split a String
Medium

547

16

Add to List

Share
You are given a string s, a split is called good if you can split s into 2 non-empty strings p and q where its concatenation is equal to s and the number of distinct letters in p and q are the same.

Return the number of good splits you can make in s.

 

Example 1:

Input: s = "aacaba"
Output: 2
Explanation: There are 5 ways to split "aacaba" and 2 of them are good. 
("a", "acaba") Left string and right string contains 1 and 3 different letters respectively.
("aa", "caba") Left string and right string contains 1 and 3 different letters respectively.
("aac", "aba") Left string and right string contains 2 and 2 different letters respectively (good split).
("aaca", "ba") Left string and right string contains 2 and 2 different letters respectively (good split).
("aacab", "a") Left string and right string contains 3 and 1 different letters respectively.
Example 2:

Input: s = "abcd"
Output: 1
Explanation: Split the string as follows ("ab", "cd").
Example 3:

Input: s = "aaaaa"
Output: 4
Explanation: All possible splits are good.
Example 4:

Input: s = "acbadbaada"
Output: 2
 

Constraints:

s contains only lowercase English letters.
1 <= s.length <= 10^5

*/


// int countDistinctCharacters(char *s, int start, int end){
    
//     int hash[26]={0}, count=0, i=start;
//     memset(hash, 0, 26);
    
//     while(i<=end){
//         hash[s[i]-97]++;
//         count+=(hash[s[i]-97]==1) ? 1: 0;
//         i++;
//     }//while
    
//     return count;
    
// }//countDistinctCharacters

// void minDistinctSplit(char *s, int left, int right, int len, int *ways){
    
//     if(right>=len)
//         return;

//     int distinct1 = countDistinctCharacters(s, 0, left);
//     int distinct2 = countDistinctCharacters(s, right, len-1);
//     // printf("d1 = %d d2 = %d\n", distinct1, distinct2);
    
//     if(distinct1==distinct2)
//         (*ways)++;

//     minDistinctSplit(s, left+1, right+1, len, ways);
    
// }//minDistinctSplt

int minDistinctSplit(char *s, int len){
   int *suffix=(int *)malloc(sizeof(int) * len), *prefix=(int *)malloc(sizeof(int) * len);
    memset(suffix, 0, len*sizeof(int));
    memset(prefix, 0, len*sizeof(int));
    
    //left to right distinct 
    int distinct=0, hash[26]={0};
    memset(hash, 0, 26);
    
    for(int i=0; i<len; i++){
        hash[s[i]-97]++;
        if(hash[s[i]-97]==1)
            distinct++;
        prefix[i] = distinct;
    }//for
    
    //right to left
    distinct=0;
    memset(hash, 0, 26*sizeof(int));

    for(int i=len-1; i>=0; i--){
        hash[s[i]-97]++;
        if(hash[s[i]-97]==1)
            distinct++;
        suffix[i] = distinct;
    }//for 
    
    // for(int i=0;i<len;i++)
    //     printf("%d %d\n", prefix[i], suffix[i]);
    
    int left=0, right=1;
    distinct=0;
    while(left < len-1 && right > 0){
        // printf("left %d right %d", prefix[left], suffix[right]);
        if(prefix[left] == suffix[right])
            distinct++;
        left++;
        right++;        
    }//while
    return distinct;
}//

int numSplits(char * s){
    int len = strlen(s);
    if(len==1)
        return 0;
    
    if(len==2)
        return 1;
    
    return minDistinctSplit(s, len);
}

int main(){
  char *s="aaaaa";
  printf("%d\n", numSplits(s));
  return 0;
}

/*
input:
"aacaba"
"abcd"
"acbadbaada"
"bbbbb"
"aaaaa"
"cikohdddhfjhhljfkelfaeiaijalndjhdhoooeocalliemjgaafknjiakgaobffhaofglhkiefhigacjoehcdbhglgckadkmnnomfmealkffchkbknnbhbiokbiaejdlgebnocbdmahalnjdaemhkafnnahgbbggjlbdkjoghigcdkcaifadnciffikmebkneeciddlofflmiligdaacclonblnbebncojldbnihceoegfnhjifohbioheabolibldedagjcfkleicdghahajfmlohdnkajeanijfofgmekgmjachknddoiaeibokimggenghjmhnmlbakbackhabkbdmihkbmodinggbnjonlkaogdoeijcoaebhaaehgndlngnolbokkfcoanlnochnfklakmhlilkkclnhhfdleedddbjiknabcofiidaijeelgdkblheciogfhhennjneckedmcdfddjckjfnnmjhhomahcmglnjiiegodgmnkngjomiajnjnbajanggoabolbkfdoelbiegeaojiehblienjlemajjbleildikkmddjgafkdgbnfongemelgmfjeeiaodgimbbaackffdnakkeiihnoogneciodfkggamehnacenfkeefcddadknaekhhfjjjkhbnmjciojacijelokjaoldgfbbakligodaccnkdgmnnoicgdcgigdglbimnbkcamoicgocacannedihihjmfjnahobejngolljmklcchnfcndoncbbibmiggnkcanekdmmlnnmcmkeecndafilgbnngojofnelcebkaeejojfegholkfhlhaookdcjinnmaaaebihbbakghdcieljiehnjgifbogkgbjlcecmlemkmljimfdoolcgigclhfdlfeaemdcmodjlhgbcailaccecgcdlkimdjhdibmakodkckggggndbimhlojckchdegbkegcongjcfblbgaedaaijflkkiolmaohgbnjkcgeiegnahcldojejkfkjihodjillfknhdmemfkficaenekechkaiaianlhfbahcokliffkoelbchidaakhmejcldbkobghlcojifabbmkbnebenemjjhilgbdjobllbcgikhhifdoggaiokimcjlckjmhhlihkkndjemaljllgcbnmgbhknofbbonlijenhkfdhilcljjcljconkkijldnnfloebhhefdbbmnbaiaaooenbinccaeonjfjaecndejkeajokidcamdabaiakcklldcjlgfnhdcnboegamemjhnheliodbekibgmbodekjjidkleofncejgkmoiehhcijngfdmenohhghfobniehcmjcanggnaiimidhnohokhelligffkdchjijiniefbikhjfjlabibdlngonbjglkfollgchfmnmleiimmobhmdaolidlmaeaoafbdnbiaabejolmcgbhjkffjjfdjejgahmiiambcmklhcngegmcjfcdahkaokdfgfehgahfckkmimbonckmbjolmknamcnjddimebhjobgibfbfkmialfcddlakdkejfodhcghddiolakmckljckkhlflkocikdhidcfcjciffhmakfdocjkfjbfafgagaicloodflikkdemniomdcjfbojmjfhnfeiadoflcfcklkdebhbgkgikcfcjfneahfgjaoaidlakknldffiejkgbjcclgkhmnaobheciegnealhlcfcceohomckdghmdmggbgnaecaibigodjjjjobfeecegkgelmbolimaaljkjlkgmceemalakbeeogchijeggefjddcjagodaljalimdodbikjjacjijflmhfcmhoijmbfenhgdbdklmdiinbnjcmhnagjiblbceiaiadhcchehgldhejnokofcohicobcolchmohodejnfhionlbinbedgkgkfcmokmkiddelckfkchdmbfbbnbnadkebljodheeofadbegjoeldenhdjjkflamancfbbcnmgagmnimjcnhadoidnhedknmhcokflfcodehmadhjkbnmabhanagodkganlbjcmgmdmmhbkgcifdlbkohacafofdjkjamdigldbjclkkibimbnaaaggmfgmhcdncljfjfaeagjeiodbfclhehaehcconblgmglocdjekicjkacdmjoejmmojojlbggjolffdajagficblcemobaoemblddccidkcmljfggjbohamegoeenbmffedfkidkfflkjnmlgbcchoickohnhnhdbjkkmgcbmjbbegdfjgiiamjfggfooakhneeejjfjjbnjhdogelcecgenimgbhncbmnklaicicdjbcbdngahfnhagekoojefhlbnlkihnedlfananfiollellgmgbkefnikljjeeogkaimlcakefcnifakceojemblcmegnjmhlblelnibjccfbdnbjihbknaohchkbabdieaffcliicmncdldoafhiionlhnbbkijmnalcahfhdjhmanlbbkebejdlgajjedcddibkknldmdanflnbhlakgagednhjcmgjccinjeolijlgmijdnmhajdhhmgcclaijldaiocfgdeomaagejkfkklkedlaenlghananmgdkcoocddgokjjgbflanjdlhhoklfkllfoflfedknecolgffahefclkmcfcajbcncjmllimgjneaiglcolcaamhjedggglngmidokikjjehhfgeoaiijhkbgmmnnagkjafobdmbfklfjcehlfejbcnecdikjehjelcahfmefdofbhlgnnfgchhaclmaehokllleeeameehhhifnlodndjagmmjadgkfamlnbnlfeddnkgehgcmhehiegcaediichmningbnlalnmlejlaoooabmoimimgljnhfnjedabkdikokoinicjcngcmhkblmffgobcmdndbafjbfdbjfdafhljanncedhdojbbhonnhkkicofidbfdbmhnaaaaicaalnndlkjfbmbmnmickmkbncodhoenhfikifiaolfanjccglblgkidadbiiflcldmanmbabgkdjoimomcjlknamcleoaigfeconhmjligjoaljicjgmgekacndljmaajiklddflbbgoaellbnfcibonhecbfhnjnaimfcahdlhkhldeijikobeonfcdoacdbhcllahigdfillooghdhhllbkecbohfnkmhjjmdodifklmdlaimgaoaeoaobfebkbjdfhnhoijfmoleoimjiigcakedjhfclnkjindleghmhldjjiafhhhleinecjkgadoggjlocbnmaelljekaaomghmfgljoohmbbjbndnimdhiknacdcbmegafhjgohomkogcgblhogbjcblojfnmmlngekhmajnamhacgjcinikbgholakhlmolemgjchbbloeldkmokkggcmnmfhnfhmbkemgmedcjihoihomnnnagmjiedlamofgekgehdlfnedimacnbmoaiobjeljfliehkoekbhcigifmnifefdfmllandgdhjnkbchkaenghhcienmeefmnfkjbefmdfohfeeihddlmmambamibjihidfeldngohiahjfkccnagcgofhnodcbnjghijlfngiedikonbllgljebbmmgifnlfgiihhgnhighkaidjdembdfcoglbcibcehoeaiecgmdocgahkahekaigbihimbbhhifjmhohideahjmdbonodfjbdjldfjfmhdnabkndgfdgdkfbgdjngkhbogdbongbknegcbbbemnlehchodbjalojoclklbhfnjjnggmnhecaigednlhijldomaanfcnhnnahjakimoofmjmighblfiijngjeaenhfdehghflmofhjmnfakbnefgalhgemaocdbcbccneonejekgbkdknblkcahggobjinbldlcfidnijihgookddndfdaemieklldjllchneijfkklaojgkkambalagkahaojhfclkdflhdhjjachkbhkhmcgjgjhaogmlfonffhifaooiolgocllhakbgbaafbafihfanljfdafoikioflfgkcmagnanenmdmkagoaddfgmiafgmmefaekbonkidjogdcmmnimffhjngihhiklmhgaanhdjjacoboaadeibcijlbiidjmgncgofebfbichiijddjabejceookbkhcklieofbhmfimimmfkbceinfdfohnmmkmbjlfhkbobmmegbgbfkooohhamcomnbijhackgdcgaljbgjabkbmhodbgnfhcbeckmnijbicdakakcffkmcgfchobfdokjjjdfbgbkeeoobmccnokllgkejghbhfdoogleiaodnfgelcagifjnljoinlandklofeekcmllihmgbibkkdknblhnhdmiojkdmdkonboiojekbkhmbiageomjiedbimlnagdimolalgkddhdgojmaciacfhajmcoojdbcljmbeigabclhkfkfbnglkgldfakbfmjfdbmkdglimgfnedjlhlfdfdfiiofhfmeehelljejjnchamlcehbcfakjnalefedhjdliooojaanfhgejcdgllffbkmffbencjnodfblaheghifabegfincbaknmlofkafjoclcgiaacflahdcbggicofjdffkdoahdmomcjecdocfhllhmlhflnnbbcbedkbcicnmkjnhdojkfjijfhifnmajnlifccfhjejjddboijaancnofmchackokobigaabdokggibdkoogdijidjgldffekjmkohkedjbghbejmmahkfjjfechcjnoaedbfodacgahjlahfeddkffoeemhnmlnbdcfgglndknlfclmkfciiinnleglanoiicgchocfimkmjdffigejiacagjofjecdnoledddbmjhjblmjlhfocibjcgoemiigmmjikflkengcndmackbidlgfakbobendgkjoendmhdgngcieiigclgdeolnnleloejjabjdaodleiemmlnkieijflljicafodenooammgaoabccodljmflfdedclggchdaicdilknbfnglihnfalkdhkcegbngkifkofnckokhafjckhcdljocjnjmemkeamljmggeibabojdlegghmhkleakknnmmihmbfhmibkdeekdahakbjgmhmehdlmcgmcjkidbhgocnjcliclmeocokcogfcgkibhjlianjdjflklacoojffajkjbjkgcingdilhefhibcmgijecgikbemoecehimecfbnafjnnmjbghdelojldeojldbeeockhcnciagoojgcehckjieckjlbbndlndnlemkcanbfkmnhfliekmfoibelamnhlgcmfeohicbcoblecmmghhnklbgmgneooimjbijhblghojlmaofahhmhbfmjbalongbhmflafcaddhdehibfgaefaoabjnbjmdilgjbjekgkimegjjhghbdhfmebkodmkdibdllnnnilimeglkljfgbbdlmaicmgbcomnmdninkllhhgfkjonohadkkjbeammamonibcannnfhnacgmehhgkkkmdahbdgbhbnnmjobjedhoeebjhafllmknaijecgkmgjfagjlnkcchfghenkflcmiinlbhokgckcffoegiceblhoggkahiilceiljdancgjodkmnblcngjddcgfgjamfcinenkemffodmnhgmhhhncjbklaglcoihfjoljcnfggohkekhgolcomngdenfiklanmeahibmledhkojooakkjimjoedjcofcdmkjbhglmckmffhedecajjegjmbighkjhcmflamkhjaiejcidndehkcekminlaeoinekoaagbaedbhmgcbaldelfabhlhakogddbfmbcacgccdfkkmjngncejgejjiniflgnnajilgkccfcgfkednedlmdlneichfoakbilfgefofmebgabdjedikjnicokfifmiilcmfokilkofebbjcegnfomdjhncmglmgnfccgakoebfecodogkdbeedbhfhfllebikgnohkonbekmblflbeadfahkbhekooelljoifholamcjmjnlcmminhkgfmihmhjboodkhcolldjlmncooblfikngnfmgiigjckaebenmjibbkabakhockcaakgacmnnfjdgalgnanckkfelilfkcdddbfgbjeejkmagkfoeehoodcjjgkhilboeffjkhaoecclmgoljlefajmjfidimikekffoemagfkedfhjdfmflkfdlbalgjahdkklefikmmdbkneifgalokfilomfabjkfifocehiohnlejjmcbofhjmfjojmkdockmngnoafnhiebmjkalmjbejhlechbfcljgeibmojnbfgnioimjidfdbfbfbfmoheiaefoiieieailelkcjbofdbjghalcolgchnaemakkeemmnbbachfjkncdfilgmigojeldeildjdgeggigkmoijeomonnikbeoceefekifdikdaocclkmeklnggcfongglblijckllmlhbggjhnkaiejbkcmmjlmkcidbfjdnhkabfijfeamljghldflbgjkdihgdbkjiohedicmlgaehaiobbifgdhkadlcklejjdgiahobhhgakaaeencdgohhenngliehdicidfiebmbhgmhdganekjamhcdnneficbbhndjkgibcheedoemaegimjcaddghljeaoccmjdlidjdmohhlfcfgjcdbflecbfheoimcajmdkeigkhnoogiaobldbmkiogahnmenhceijnolmjfaegihjgkamjfjjafldhmdnfgddbikmhelkadknhgbehnfmbcakgocmhjccenlakcccbhflnjiogeoohbhhjcglgoifdgmeheobmemgonadgiddienkljeekkhegkjhjifidgegleeaonaaofnblnlhlknfjnoljdabkijamfbfnbbmhbiegmkcmfeaicolfcbghhgcnjkealnfglagbohfbhhdinggjfefhcebhdhlkmmdbconileecjkogfloamiimgacjoaogfmkkiimliemladlmnddlfchdbljbonigbmdeaekcmcokkfdaehnnjhadmokiidhodhliglmaeoeiigeehjiahkdifdjmhfbijcglkokkajiaidklfankoeoigcloillhjbbkjgoejoelcmdjklmfgeojcnbmhejnknndgibjbnajaonbodekmjjkngmnelhobdklblbadglmkdoeacecefjaainbomnkfjmacdfahodgjdiobflihfekcmhdlimlgkmoolfcafbikeoammekajokbegfkneinhahbclamdcdcfhkiijbfjddhgaffcjnoajbocfnflggejgcijdaimjhmokgnmmckboiacdgoodebkojbjdcejkhelielnligicijgakihoglkilckijlccnjhnomhicohfgmcfkiafjghallokcafajikmbigckmflbdbjiidhjnfdhcmfekilkofjjmkoanfagfbnmfailfmcfnicjfnnjdjemgbemlaalfdjdjjcahjcadbihlijanlaffjjlgckllffalioihihdbjdcakffcgeegmcokbeoafcamlkfciaehaibdnjliofclgjcgoimcfobhncndjghcaaanagjimnjealgaokcoffdnkidhnadbkfcoohmcglbkbancdlohchjahjefcenaiemjoachljcfemcdhfchbihnhlncdoakhjenadembjkbemghjhjljgbmfbboaldboaggfnkobfhlkicclbjahdnjgbligjdmohbdjffdccdjihchaooinkmlifndmjgnocegdkccdjfigmobdfhnkmjehajhmahadeegicljajaakagembgeloibemofnnenbgjamldclngiojlahcomdikmkalbmhbaoacdbhdmfggebbjgnjmooolliaikndfodahddanibdhodncmabjinidhdamikedlbifnfdgddhjgaioheoadnfiicggknjgchnekfghihjeoladkebegomonoegnlbaanedkfcamcfhgdmdmnomhcobkeofiodaenonefoaknljhkbmlgmejbjcillbiemjndoieojmjeobiiblhldhclokbbomccnobkjdmjcbchngjeahiajlimeekmlaneiedikfihcoalgmdobmeglfefekkkgggkoneglaocgejlknmgmhbefihboihfjhdoihdjdllgofhbocgkljicdihhkdongeldbbfbinnjfcmkjofmgcocklfjeneajdccdgkhmmbglgmldjgigcokajhdhhfahkjhhndgmggemaaaiafcfjflemlnlaiimdklanghfehmigammhnnghamjanbbioflhgmndlldmjegbindkloahoagmckihemldaebohidfjbfdciamommijflhfminkdknclejojmckaefedbindkmfbejiigcgbfeoedmoohajhbhmoaldbcncjjeffajkjnnfgkinkclkanhlejlggdobeikjmhimbbfjafjjfiofammgcnjgcdaanoegifcnbhbbjdhdjninfaalokfiiobnkjdhhledhbcnikmaclnfdakdgianmgfnikhhmamlecbmfdilcaicddekoobhfcdmhodngfiaahelmbdjigdngkbkbgkinmlkchccegimjdfcifdiihffeldkckmkcfhkgocblmajfcikonodfmkjeonfobkoojmadifbedjkjakgebflgbjeenoojdbfbkjcinhniibodfoldldeldeajkieklkmlnjgcokmbgmilcefkkjibdddbnefodkaldeibdkhifloicamomhocacbobmendbeffcbjiahefiajcceahfookhiflmcbmckfemkbgoiokdadiidkikhoakomloaemgblhinikgmcoebiimlbgjgehjnnadbhocehejoilknckegdhobndleonignfjekdbglgdhldcladjhmkdmgddiionnjdacoemgjbkekokbbaeokidfakofmheinkocnklfdbfbdkjngcilekabbkhdonmfnfndljddhiiiiehbddnnlmaoggnfofgejgdomemeknmmdgimfeeighibclglkoahokeknkaadeacinadgmdihamgekkfdilhjogkhdkejjnmlgdhjndeomfbadfkgdogghknekdcgiiohclimienkdlmcogjejdihlnomgniefcnhkekofcojiofcadnbnchhmlcmadlbkjekdcihjbhdjidnaannnmenkbigclhcbjhaccicfimkjickfifolgdiaiggcmajledijebioijdlbbefaobjdgnolomhcfkdhekdibcmgjlmbldkfejkbjfjdhfiimdadaaalbcfhaokdihnecnajhfombfegoabbimbdlnaadmadjndofffockkemnjfdnceggckniofcfgoodhglokfnmingoilfkccaaadjocjlmmdbghiafohggbbnhohebkkacmmgmkncmliaagcfclkgfckfllbdcmjheoianlciboiolbghbjmhneeifajgjfeocdhiicdgkaiadddamfahalgckkejjcgekecaafnbhnggabcconljhbfbfnbgmljengbohkolfiifeihgodngdbonjakikgfjefgaeaffhnjimdejjmocaiijdamgdalogmblohjffnamjjkhbohcdkghhbcjkgbdljcfljdeaibmkohfnkkdkdddljhgfejlbjdiafnodlmoamiofnmkcekjeojlefoghlnmjnggffbebbjmibmkejgbiaiamookadljhjaoohmjjjienahmikdcfjedcfeofjelackeomkbegmabhdcojjjndgblilnnbanmdfklfeobnbbhdmocfglmbffeecnenackeccniddbjmcgebjjhajabfdgonbhldgbnbejjeojeiljdidanehogbdkinlajcamjnfjfdgkfjiehiaainkckhmcjklamohdobfbanfkbnmkjceahedbdfhkfmjhbgnnoddoamanbgohmfnohaghjmgdjonikladglhkljekejbgkldhkbgjjhhjmjenacbcelihncmnhgoclkafkhmkbahadjgbagcimhhdkbjfjjjokdliobghhniofjbackmlchaokjkhjgllknajkjdgidfcomginehhcfecafgmkhmabbkndidmgkmcbdkfedeiifdlfjgnibibhkcdljhkihbjbkbedlaohchmaogjjfdgfjdbokfaakfigenalodafabkefoifmoabafoldmcgbhendfnogiikgkjjfmigmagmkdcneijgcegbffakbjgniljljkiddglccnmfdfmejeanjjaefgidlngnbcmakmjhhdmbdchbahgijfbekbblfdehfbijocbmjlgfkbbonjbgojnmninhkdcibegekjklilfladkogjhlmfbkdbojedckdcfmajmhhejefkcclmjgdkaocejekgjglebbndblcmiakmbdfmcicehjijeddjjlnckbbbgafllhhdifaafjhajolcbiflfcgcgodfjnciomkafbhlnhegmheenachhlikebfhhffkakhdljjndmamdjmkhbgmjdoejidfefomiemebjgoldnjejmlidodbocicabjeikmallbbdemhijaiienacfomnfabeelhmlihhnkkjlgcklfbjjcifjhdaakjifkfekhkncfibgkhegkeejjeljinbcimhbjdbkmjinmlmnakfeoehjnhijgihmcngmloiljnbdhlcjcbbmcjkceffhkegmfgbamlefkgkhdalnbibbhllidjffelagnagijglnlllgambbhecjojeljmcfmfndekknefbaeagocjcnglmjnfalajcefkaoacfhnolebkfghkhodmfnencdlankkoeliichlfnbefbiggmhilfikbcfmalddocjkfhekfhgaidnogkmiaeaiodeddmgenmcncogoakoojndnccflmmggegimfnoafieafakmbgalaggldjlgfniljidnagljglkejnkfafklmlnmaeedkdbmohbinejondahgdjemhbfcbgagcdgjfaaabmfejfdjhnfegngloanlbomehcffmkoegjoljlbhdhofldlbhiahcbigjjjmkcjkceddioomenkmgflcmkgeokohhlmglniiolefeenglggfhbcddkednmakjgbgecbjmenbdeiokhgkfbedcjmjbmndieanndnlhdcffnhnkdlbimgdllmihiagfncnodhjocbagmfchccfijeaadffaiigblijfmfgdfgnfglahblaloeejgabgbkmnabfdchnkacmonakafdgjdbfoalfhfkcjiiijcceenlbahfgffgcdgiaamhgkbhgdiefdogbogfoboebcjgfamailjcegekgnbbdncjfagibdeoidcaognkoabhkogknfnkohhblolgndadaohlkfakdbnejnkojhdhmjgaoahkleijjaofmkainhociekgcnmdjghombadhhfhkfmjhedebanjioblfmnafaogoecinhakobmoingdadcchondneakbigjncaelgciinacdidhmbnflmogecbbdoagaelggmijneokfcgnigcgjdnoidhjfdaodmmcfjnmcnhjkbnlhnlakndnllibblcglbigjjnboagagdakdoneomongaaoefifegdibmonfjalhlechgbfdfnigkkddjbfejemajgnnbgggaaknhinjbbolimemgolgfhbnfnfaeoeiaaibiibdhfhcnllgfleablmacejichbklhklidodgegfflmdjgdeomlnkalofhdagnocflafmodekcfhnojnfomblbdbehdkifngbjioniggibfefdflcggblhcjjmggbhgkcklibbiemeokhlcoblehkdjlnjcfjmeohbafbdnlnbmaocnoanljnjjdnceemifodflknnmdlcelfihkhfbbeafcloiiljlbhclcmkiockiccdkincmelgldhkibaenbfbikgcmhhjmfkgbdffkabbnjccnhfelidnnjofembfogoidgefcaeahjnglcoaegfniekbnobjfmmofnoajnbmkmggbhljjbcjkkdkkbkmekgflghlichdokdcgjhgjljkadckibkbhfekinnjdgjgilkannaifehaidikiifomjojeconnnooehbdoinbohjkjfelfnndideabhohnicccgdmbfoamjcnfojmkbjjnchamkfcnmjahjmjichmfoeodamhkmaoigemalcaoijhedmljhhgjdfacjlhickaklaefbbeabaadgbmabaaebkiihncamaijihbljndmadjekgdndbaigalnlnliadhakmfkbhojnoglbmjohhjhfcmmlghbnooamnnaojcblcfcobfkgjebmkahindfbiieekakeajollmnlkaancdakmccoaecfolbndcnckhajdmamhbddjojkgeojinalniakbfnennejlmjnednaoffhfcdhjkcegonfkhmjelcdgkehboffiheahlalnkcakmdamolhkjkghihchdbnjcccameifanhlnofhlodldhlinjfiglgljeaeacmgedlkjfcdhkegaiidaggifnnndhefjleljddijgiflikeanfngfeccjlaoihfancbofgendcnnckniockmhhdimkbiiolldaafandijcnofdemihadbbgboafcjmcfklckkenedhcloiemniflbhhoklfhikmfcbemdmkokcmmfihgebhbblbedjjjiadfjabciodikecefhnikfhaiohchbclonhkifhnccmafddkmjlalacoajldfndmgfmifggmlnaiddonjojbikfhkbekdbdbhcfiehffabkaeemnaboklnaelloifeeniojdhbinemjgaoeggocblclcbhjeicmjkhnnjemeffeodfkbklkhogefiaicndialmmmbndijfclncnemanjaaaiidifaklidmchkhhlgfimhlkmlmkmekellhljccjicmbnnfkdjkmllakkfdnaagiljebfhoajgahkdnmgiollljfgihickfoajhhhoaladdnnlblajihekfgelefdabaoonjaajlcghcabncmfdblfifjmoodcbmanmkidnlfjimcialomfikbikjhbkcamigggjncdkiffghenfiljigliioanooilimbjefgejajjgbokhaodjebbcmnokjonjenlaoihbhdlgbcgdelfbdbcjknemanohbjjkgagidbicobammkfhliibodhgbmmeaebgmifibgdahbmhcjndadenjkobaibeceoefihdncoghbdmdlihfefhbleoekgnhidbnfhclijkacambonifbjfoihkjddljfdihcmcglbfbjmfelmmdikhmgonilkehbkcbbehicjhfcloohciojielfknffadlmclakgfcfglkfbcmkeombfdlhndfhgjaciknkhbdccinodiojoogginnheeomcbadaidbfiolkgomklmbagjkoflbggjkdjknnehmdkkjlebheaienmgchoilcjejoogfdnfgnlganmjoflhneeamefnoccmejdmcllccenkhabjdfanmblhdmmgjmcnkdabbbgnkmjhgcaaejjbidnecbjfhaeciaobghmnbmciblmohlibjkniimjdjkoodfieimglogjkignfolmilefeikmndneddeoofjbcogfhhomnfejjbilgnnhgngflkannkgfocffhojfkaghhjdklfggaemgbhegaangcdfgdjhanjhdolfinmfnindlmmmbbfljicbmgiloiickoenjkkfchgckjohemgelloafnellccaobfmnnfeojldcmbbfodhgliefgfbjenfagklkabfkofkecakmcigjgfobjajhjkalonleoikdambhbogkhlhojdlmaemahmmoiifafkofimnalacdhdchkdncknlocfeclefkhjmgjohciefkonnmfbhgoflgndkaklgfjdagmogaoijmalnoolbfnokckcflekalekhdlocgnbjoefccigibkbjobgommjhelhlcmeeojhilhmkfgenhhemgcoalnjghgefbgindacacaodalnhnoneidmbehecalnmklhglgmabahllddehgcmmcmchoelangcfbiihcijjbbhkobnhngmkeiljhkdianmdeiajdbflchghhhjjogikfomikalmlcfkoncmfacjfhnfkencdikoefbgenngioiochjkfdcjggkanlgenooifmbjmlmodneilecmgebolmjmjjfildcehnkhmhncnidgccejgcikebcenncfbfcobffjjccmeboojgjeghdedemoeldlkfhjjickbfjnfiajcjhojhbliclhhbboneffhjdioniccfomdlkkboncabjgmblncdgljekiikhmodladmfdeffannjalcneodeljfimocceecommcocbjoacnbikhbchniiclijomdjlojfbfkdnjnjaggjeokoilifkfjlfhidmaodlkbojbjfkojldflgamlefodojeigadienmihkcmkimdmfnbjaldikemfcgdlfdlhihklhjgjgegbekhfoghlcoammliiadbfcijnllcnehfihagfmecmjfflcaecoobjlmjkneghaobgcollfjedfkddmbobnkihkeokelaebgbhbfoffinlhfglkjbdjjelknjlnenfhdgdgiianbcohkajhlejlkadkdmhieffncjboemmeaebiijjmegafleioebamllieijnfahfieogaaejibikcjodlelanjegdmgoiiabkbhailjfjjbjcbdkedfblbdbaehjmjikjiekjcnlhigdelcfeccfbdjgefehjcikdghknjogdgjmjjkfejmkoilbigkoicigceoahhdabfnbmiegjmbfifgimablfinhoimfabollnjgkfkmofnmikogamggkfdbjdimikgeehioeibeajnggkbmbkmdallladobijgdnkmhglgogdiknoeegfhjfkfhclgjnndgdjekgjjgimggolcbikembmonagieeccjblmmhlojbhgniimllncelbjmahlijiaaejkgocekglghibcaideabechegabkgihbklloidiknalglcnkcdacmdccclhdlbbjncbcjlemmmcmkmhimmbbhflffiefhcnmfammlejjllakelnfknfboebhbdcaneeaiahimmibhmodbkclkjhkebcfhaojgfhdjedjhenaeangfhhhibkjidhcodgjcjoifacgcgdlanilejojgeihacbmjnogegnngolaogkmalghlkajakhmokihminnnahoffmenbfaolblieojidonicjfldfmbododoaccikammgjcmgboeoebbmlcgnjhbhmmnjdhagmbjoomkiafhgdjgjklelghameijfjgbghcfmiahchemdnnjdgajehgiegadjbejggoadbeeahcihhdlekmlofbjnomnbkbannfkeijfjeknajoabfffjckgdgblficfjgkjnebkikkiafjhammlgcjoifmijcbjliolehbonmngadogeohffakmefkdincikkadjcoonijmbgigiomcaiijhhanighkmdljjnknmfmhhhenhgkohlddlbfebaeoiaenoebcjjaechglkbhmgolieelcbgigmmnmhnaaaojekndfdddoobcohnafocdbldblbaggnhjghaioidegcnojfgncfnlecoddilgcaonagfgnahhgjmkmamjccllegfkbeifdgbfomcnmiedklifccdojbckieglggenmjlocmbgmlgldnikbbhamgbeogafmiomnomhabddiijodnmbaiaahlkdibeegjingedebnjglhiidmboaekckdbbankekdnkdbhellkdlgbjohbjnbjnjgimgjeajmbfjoddmeojiibgngjdnadbmlnaifcajjbedcnmkhjjdkmmmiahncalffjokachlejaacbgjonfhcfjnjondachmnfealieemmndjnammcgfjcadkgcmknofdfnbamdaifacfohlgiiddaoialidfadkjadgimlbdmhneajommfgkmhokdehgmkaflegbmedhkbjfbijegaagbfdeahndblhiggajefacahlghncjeanjkokbdhcgnikebmhicgfodnhhoheojckjhhdggnfnkgiocgconmjghggodbgmbbfnaadckdblellnkokfgdlokjodbfcglemkonhgbeehafdmncoohhdbcclemooghkonhhieecmbbgdifbklbchbfefcaandaelchhiginmbodgonlhagboemfcdbdmkmekeeijnddiakimaeommnjnbalahcneogeibkohoheejbaekfcifekfnbcnddnnndfflaihdecklhonkiigmkhlcigbikdaimikiejbggkfiiobinfbdbeillchfgofhhfjecanddmkmldbnlmcjfkhbmkebhffabieghkfmeaannjcnaclohkmmhecbicdcbilfnfcjjjnfgamagkfomaenjenmmhmobcadbmicennfmmegjhdjaikhiihcnkbjdimfnokadijnklhjogjbfcaheogijeddcbbfajoodknfekhffjgiimgnlidmmfhdcbcibmdlldkecbkmlfcbkgfnemahjjhfkhjjcafdbmdjfdkffcekhbbbgcomajjoclalgfjobemmndifehaoifkoojkglkabnlkhjijhbkiocfafibhjncgelahmfefhfbleeokbdgjfkfnhmokmeifkfkegbafohdohllaloocfbjldgohbnkilfdmcceofehebbjfnfdobdchhleahjlbchcnidkndeibnobajjnfnfhhgdedacclhaldekboalgohncjefoelbbeblknmkefmobofibbdkcfmbajbhekhgahmmkdiofhlfkaolmebgcfgfcfmnehbblcbnklgdjdhgegioodagigeffciikageoclffkkjobfjimkihhhmmmdlgomkjjibjnbabghofiabanfedkaaambijeedaoknnnncnmbndbajjcffeefcjlehmakakcmjkdhneeikcaoafmgaackccijeligfgbmgmjhiendleedkbmenajcbhfhckogloioookgjhcijmajnbkefmgihfdacmogahgkmhlbhnoaidinffbfdjbgoekaajobliboifhjhfbenhmoinenbfebcgfcicjefheiagfgangdgdlkalclcdgmfhijcafafdikeheabafijbofdaglighejlolbijnjkjdneoehobjhbbagfflnjnialekaialdebkdeiehanhegbjhjmmjkghkalgfikciaehmbldjoaaflkibbdfciaikhfhmjcaknccjgggjnbghhijbnemoagfhokljbnnkoimjelbcagkomofkbjbcmgocfogagklgodnoecmaocdhbcdgdfgindohoclcfidecimlmfdngijlajdjflhgnjmkkhjjkjmhccekofnemliahfjhjofehebijkcgakmkhadcficleeeoclibgembdleebaeckdbaechcccfmlhaoiojfjmcjgdfngimdhgfekaacahekhdahflglehmaljngadcecoafndccnolbmgobfojdojokoenhacdjhanjamjokinkbmaekjkalfcbfkignicekljfagfbdinnheejannglomdmhngomkbjkioilhmamaljnkgnimcahickbhejbfjjadonifdbfdfjchegnnjdedihcoldfifdjcfnfjkbadofljmjhocooaldjioddnjalihdnfhggmadlfdeigfgeeflgdnndefcaccbhmflmoeligdoognikmifacmkdkdclbaekookikdhgedfangojcacchihdimejbgjbffkejmmcfgdcikalciaifmlgfijgnibceljmhokbnobcjncdhaneekojkamdgoadlbdoafmefkbhlnhicidm"

output:
2
1
2
4
4
18664
*/
